name: React CI Pipeline

on:
  push:
    branches: [main, origin]
  pull_request:
    branches: [main, orgin]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test -- --watchAll=false --ci
      
      - name: Run lint
        run: npm run lint